//
//  Constants.swift
//  E-detailer
//
//  Created by Ammad on 8/3/18.
//  Copyright © 2018 Ammad. All rights reserved.

import Foundation

class Constants {
    //        static let BaseUrl = "http://192.168.100.101/"
//http://novo-api.digitrends.pk/
//http://novo.digitrends.pk/
    static let BaseUrl = "http://novo.digitrends.pk/"
    
//    static let BaseUrl = "http://novobeta.digitrends.pk/"
    
    
    
//    static let DcrBaseUrl = "http://novo-dcrbeta.digitrends.pk/"
    
    static let DcrBaseUrl = "http://novo-dcr.digitrends.pk/"
    
    
    static let LoginApi = BaseUrl + "Account/Login"
    static let AttendencePostApi = BaseUrl + "/webapi/AddListCPAttendanceOfflineVersion10"
    static let AdverseReportingApi = BaseUrl + "DEUWebApi/AdverseEventAEFormSubmit"
    static let FileUploadApi = BaseUrl + "/webapi/FileUploaderWithUrl"
    static let ContentApi = BaseUrl + "Account/getcontent"
    static let SyncHomeActivity = BaseUrl + "DEUWebApi/PostCallSync"
    static let AllPatientsApi = BaseUrl + "DEUWebApi/GetPatients?employeeId=%@"
    static let PostEmailAPi = BaseUrl + "DEUWebApi/SendEmailClinicalActivity?RequestIdentifier=%@"
    static let PlannedPatientsApi = BaseUrl + "DEUWebApi/GetPatientsPlan?employeeId=%@&Date=%@"
    static let PatientReschuledApi = BaseUrl + "DEUWebApi/ReschedulePlan"
    static let PatientProductApi = BaseUrl + "DEUWebApi/EducationalActivityProduct"
    static let PostSamAndExpenseApi = BaseUrl + "ExpensesSync/PostExpenses"
    static let Uuid = "Uuid"
    static let CreatePatientApi = BaseUrl + "DEUWebApi/CreatePatient"
    static let PatientCancelApi = BaseUrl + "DEUWebApi/CancelPlan"
    static let PostImageApi = BaseUrl + "WebApi/AddDEAImage"
    static let HomePostImageApi = BaseUrl + "WebApi/AddDEAImageHomeActivity"
    static let CallApi = BaseUrl + "api/callsyncv1"
    static let ContactApi = BaseUrl + "webapi/GetAllContactPoints"
    static let DoctorApi = BaseUrl + "Account/EmployeeDoctors"
    static let getAllPlannedDoc = BaseUrl + "WebApi/GetMSRPlanV1"
    static let GetPatientDataApi = BaseUrl + "DEUWebApi/EducationalActivityFormList"
    static let ManagerApi = BaseUrl + "Account/EmployeeManagerDetails"
    static let StatisticsApi = DcrBaseUrl + "webapi//padashboard"
    static let CategoryApi = BaseUrl + "pdf/GetAllCategoriesTreeView"
    static let VideoContentApi = BaseUrl + "Account/getvideos"
    static let AttendenceApi = BaseUrl + "Account/GetAttendanceMarkTimeVersion10"
    static let GetPlannedPatientApi = BaseUrl + "DEUWebApi/GetPatientsPlan"
    static let GetAllPatientPlan = BaseUrl + "DEUWebApi/GetAllPatientPlans?patientId=%@"
    static let SampleAndExpenseApi = BaseUrl + "Account/GetSamplesandExpense"
    static let CryptoKeyPassPhrase = "hi;Ar;Pak"
    static let imageUrlApi = "/webapi/FileUploaderWithUrl"
    static let getCallCount = BaseUrl + "DEUWebApi/GetDiabatiesAwarenessEducationStats?employeeId=%@&date=%@"
    static let getClicnicCallApi = BaseUrl + "DEUWebApi/GetClinicalActivityCalls?employeeId=%@&date=%@"
    static let getPatientactivity = BaseUrl + "DEUWebApi/GetClinicalActivityPatients?employeeId=%@&date=%@"
    static let getHomeCallDetail = BaseUrl + "DEUWebApi/GetHomeActivityCall?employeeId=%@&date=%@"
    static let getHomeActivityVisit = BaseUrl + "DEUWebApi/GetHomeActivityVisit?employeeId=%@&date=%@"
    static let getHomeActivityPatient = BaseUrl + "DEUWebApi/GetHomeActivityNewPatient?employeeId=%@&date=%@"
    static let EDUAdverseEventApi = BaseUrl + "DEUWebApi/EduAdverseEventNCFormSubmit"
    
    static let imgUrl = "imgUrl"
    static let ratingStar = "ratingStar"
    static let ratingStar2 = "ratingStar2"
    static let uploadImage = "uploadImage"
    static let HomeOff = "HomeOff"
    static let GetTime = "GetTime"
    static let imgURL = "imgURL"
    static let expCityName = "expCityName"
    static let cityId = "cityId"
    static let selectedDate = "selectedDate"
    static let currentDate = "currentDate"
    static let patientId = "patientId"
    static let ishardCopy = "ishardCopy"
    static let patientUuid2 = "patientUuid2"
    static let screen1 = "screen1"
    static let key = "key"
    static let isexplained = "isexplained"
    static let ishardselect = "ishardselect"
    static let isexplainedselect = "isexplainedselect"
    static let callselectedDate = "callselectedDate"
    static let CallToUploadKey = "CallToUploadKey"
    static let HomeUploadKey = "HomeUploadKey"
    static let patientUuid = "patientUuid"
    static let TypeProduct = "Product"
    static let TypeVideo = "Video"
    static let TypePdf = "Pdf"
    static let RootDir = "eDetailer"
    static let DownloadDir = "Downloads"
    static let patResult = "patResult"
    static let clinicPostData = "clinicPostData"
    static let LOGIN_RESULT = "login_result"
    static let EMP_ID = "EMP_ID"
    static let LatitudeKey = "Latitude"
    static let homeImgPostData = "homeImgPostData"
    static let LongitudeKey = "Lonitude"
    static let homePatientUuid = "homePatientUuid"
    static let LastTimeOfUpload = "LastTimeOfUpload"
    static let TypeApi = "Api"
    static let IsSignInKey = "IsSignInKey"
    static let imgPostData = "imgPostData"
    static let imgPostData2 = "imgPostData2"
    static let MorningStartTime = "MorningStartTime"
    static let MaxMorningTime = "MaxMorningTime"
    static let EveningTimeStart = "EveningTimeStart"
    static let MaxEveningTime = "maxEveningTime"
    static let validate = "validate"
    static let Employe_Name = "Employe_Name"
    static let Objective = "Objective"
    static let appDate = "appDate"
    static let appDate2 = "appDate2"
    static let ConstantNO = "ConstantNO"
    static let desName = "desName"
    static let getDesId = "getDesId"
    static let getCity = "getCity"
    static let expDate = "expDate"
    static let expCode = "expCode"
    static let expType = "expType"
    static let expTypeId = "expTypeId"
    static let expAmount = "expAmount"
    static let expNotes = "expNotes"
    static let expPostData = "expPostData"
    
}
